# Generated by Django 4.2.5 on 2023-09-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='participant',
            new_name='participants',
        ),
    ]
